### ISSUE TITLE
What is the easiest way to generate concat nexus for SWSC-EN from phyluce?

### ISSUE THREAD

**Issue by ghost** [Tagliacollo/PFinderUCE-SWSC-EN#2]
Hi I am having trouble generating the input nexus needed to run this program. I have the phylip and charset files meant for raxml generated from Phyluce but it differs slightly to the example nexus charset file here. What is the best way generate this input file using phyluce (or another program?)

Thanks

Miles

**Comment by roblanf** [comment]
Hi Miles,

I would suggest converting your alignment from phylip to nexus using something like the free version of Geneious. Following that, you can edit the nexus file by hand in any text editor to add the charsets, using one of the example files as a guide.

Rob

**Comment by ghost** [comment]
Hi Rob,

Okay thank you, there is an option for phyluce to generate a concatenated nexus file but it still needs some manual editing, does the charpartition always have to be in order? The UCE loci in my output seems to be random:

charset 12874 = 172719-172925;
charset 12233 = 128381-128570;
charset 1358 = 27124-27275;
charset 1166 = 227817-228025;
charset 10260 = 179849-180159;
charset 11486 = 189515-189694;
charset 11698 = 110062-110257;
charset 820 = 221517-221725;

**Comment by roblanf** [comment]
I don't think it needs to be in order, no.

**Comment by ghost** [comment]
Hello again, I was able to get the program to work, and I have another question about the output:

Most UCE loci had the output like:

49_left = 68529-68584;
49_core = 68585-68686;
49_right = 68687-68736;
Which I understand is the SWSC dividing UCEs into 3 chunks

While other loci had 3 entries that says the same thing:
1269_all = 96091-96225;
1269_all = 96091-96225;
1269_all = 96091-96225;

while others only had 1 entry
658_all = 73758-73911;

Does that mean 1269 still has to be divided into 3 partitions while 658 only 1?

**Comment by roblanf** [comment]
Hi Miles,

Did you manage to resolve this? Sorry - I only just took proper notice of it now.

Rob

**Comment by ghost** [comment]
Hi Rob yes I think it works properly now, not sure why it happened first time. Thanks!
